// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class ApplicationMemberAssigned
    {
        [Key]
        public int applicationMemberAssignId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string applicationShortName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string applicationShortName2 { get; set; }
        public int memberId { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime createTs { get; set; }
    }
}