// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class Application
    {
        public Application()
        {
            ApplicationMember = new HashSet<ApplicationMember>();
        }

        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string ApplicationShortName { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string FullName { get; set; }
        [Required]
        [StringLength(500)]
        [Unicode(false)]
        public string Details { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string Image { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string Path { get; set; }
        [Required]
        [StringLength(100)]
        [Unicode(false)]
        public string Status { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ApplicationGroup { get; set; }

        [InverseProperty("ApplicationShortNameNavigation")]
        public virtual ICollection<ApplicationMember> ApplicationMember { get; set; }
    }
}