// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class ApplicationMember
    {
        [Key]
        public int ApplicationMemberId { get; set; }
        public int MemberId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string ApplicationShortName { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Status { get; set; }

        [ForeignKey("ApplicationShortName")]
        [InverseProperty("ApplicationMember")]
        public virtual Application ApplicationShortNameNavigation { get; set; }
    }
}