// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class AssetLocation
    {
        [Key]
        public int assetLocationId { get; set; }
        public int? assetId { get; set; }
        [Column(TypeName = "decimal(9, 6)")]
        public decimal? lattitude { get; set; }
        [Column(TypeName = "decimal(9, 6)")]
        public decimal? longitude { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? createTs { get; set; }
    }
}