// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class Batch
    {
        public Batch()
        {
            PatientRound = new HashSet<PatientRound>();
        }

        [Key]
        public int BatchId { get; set; }
        [Required]
        [StringLength(200)]
        [Unicode(false)]
        public string ShortName { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Value1 { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Value2 { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateTs { get; set; }
        [StringLength(3000)]
        [Unicode(false)]
        public string Detail { get; set; }

        [InverseProperty("Batch")]
        public virtual ICollection<PatientRound> PatientRound { get; set; }
    }
}