// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class Log
    {
        [Key]
        public int LogId { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string Type { get; set; }
        [Required]
        [StringLength(20)]
        [Unicode(false)]
        public string ApplicationId { get; set; }
        [Required]
        [StringLength(5000)]
        [Unicode(false)]
        public string Value1 { get; set; }
        [StringLength(5000)]
        [Unicode(false)]
        public string Value2 { get; set; }
        [StringLength(5000)]
        [Unicode(false)]
        public string Value3 { get; set; }
        public int MemberId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateTs { get; set; }
    }
}