// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class Member
    {
        [Key]
        public int MemberId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string JNumber { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string FirstName { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string LastName { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string FullName { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Password { get; set; }
        [StringLength(300)]
        [Unicode(false)]
        public string Email { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string MobilePhone { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string WorkPhone { get; set; }
        [StringLength(300)]
        [Unicode(false)]
        public string Dept { get; set; }
        [StringLength(300)]
        [Unicode(false)]
        public string DeptAzure { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string OfficeLocation { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Status { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string StatusOverride { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string TagColor { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Title { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string ExternalSystemId { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string ManagerName { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string ManagerExternalSystemId { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string SystemRole1 { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string SystemRole2 { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string OnPremisesDistinguishedName { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string OnPremisesImmutibleId { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string OnPremisesSamAccountName { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string OnPremisesDomainName { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string OnPremisesUserPrincipalName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTs { get; set; }
        public Guid? ResetGuid { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string AccessCode { get; set; }
    }
}