// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class Note
    {
        [Key]
        public int NoteId { get; set; }
        [Required]
        [StringLength(500)]
        [Unicode(false)]
        public string FkTable { get; set; }
        [Required]
        [StringLength(500)]
        [Unicode(false)]
        public string FkId { get; set; }
        [Required]
        [Unicode(false)]
        public string NoteText { get; set; }
        public int MemberIdCreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateTs { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Type { get; set; }
    }
}