// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class PatientRound
    {
        [Key]
        public int PatientRoundId { get; set; }
        public int BatchId { get; set; }
        public int? CernPatientId { get; set; }
        public int? Mrn { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string PatientName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string HospitalId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Unit { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Room { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Status { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string Note { get; set; }
        public int? RoundedByMemberId { get; set; }
        public bool? Q1ConcernsGenYesNo { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string Q1ConcernsGenComments { get; set; }
        public bool? Q2ConcernsMealsYesNo { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string Q2ConcernsMealsComments { get; set; }
        public bool? Q3FallRiskYesNo { get; set; }
        public bool? Q4PressureInjuryRiskYesNo { get; set; }
        public bool? Q5AdequateInfoYesNo { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string Q5AdequateInfoComment { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }

        [ForeignKey("BatchId")]
        [InverseProperty("PatientRound")]
        public virtual Batch Batch { get; set; }
    }
}