// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class PrAnnualMemberSession
    {
        [Key]
        public int prAnnualMemberSessionId { get; set; }
        public int memberIdReviewed { get; set; }
        /// <summary>
        /// 0=COMPLETE; 1=NEEDS_GOALS; 2=NEEDS_CHECKIN; 3=NEEDS_YEAR_END_REVIEW;
        /// </summary>
        public int prStatusId { get; set; }
        public int year { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string signature { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? staffSignedTs { get; set; }
        [StringLength(5000)]
        [Unicode(false)]
        public string managerNote { get; set; }
        [StringLength(5000)]
        [Unicode(false)]
        public string staffNote { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime createTs { get; set; }
    }
}