// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class PrMemberGoal
    {
        [Key]
        public int prMemberGoalId { get; set; }
        public int? prAnnualMemberSessionId { get; set; }
        public int? year { get; set; }
        public int? memberIdReviewer { get; set; }
        public int? memberIdReviewed { get; set; }
        [StringLength(3000)]
        [Unicode(false)]
        public string goalText { get; set; }
        [Column(TypeName = "date")]
        public DateTime? targetDt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime createTs { get; set; }
    }
}