// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class PrTeamMember
    {
        [Key]
        public int prTeamMemberId { get; set; }
        public int? memberIdManager { get; set; }
        public int? memberIdStaff { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? createTs { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? deleteTs { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? referredTs { get; set; }
    }
}