// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class QrtCase
    {
        [Key]
        public int QrtCaseId { get; set; }
        public int? OrganizationId { get; set; }
        /// <summary>
        /// MORT = mortality; MORB - morbidity
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string CaseType { get; set; }
        public int? FIN { get; set; }
        public int? MRN { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string PatientFirstName { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string PatientMiddleName { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string PatientLastName { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Dob { get; set; }
        [StringLength(20)]
        [Unicode(false)]
        public string Sex { get; set; }
        [Column(TypeName = "date")]
        public DateTime? AdmitDt { get; set; }
        [StringLength(4000)]
        [Unicode(false)]
        public string AdmitNote { get; set; }
        [Column(TypeName = "date")]
        public DateTime? EventDt { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DischargeDt { get; set; }
        public long? DischargeDiagId { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string DischargeDiagText { get; set; }
        public long? PrimaryDiagId { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string PrimaryDiagText { get; set; }
        public long? FacilityId { get; set; }
        public long? FacilityNurseUnitId { get; set; }
        public int? AttendingProviderId { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string Note { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTs { get; set; }
        public int? CreatedByMemberId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeleteTs { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string Source { get; set; }
    }
}