// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class QrtCaseExtended
    {
        [Key]
        public int QrtCaseExtendedId { get; set; }
        public int QrtCaseId { get; set; }
        public int? FIN { get; set; }
        /// <summary>
        /// NEW, IN_SCREEN, ESCALATED, COMPLETE
        /// </summary>
        [StringLength(50)]
        [Unicode(false)]
        public string Status { get; set; }
        public int? MemberIdAssigned { get; set; }
        [Unicode(false)]
        public string Note { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string NoteInline { get; set; }
        public bool? Screen_IsDeathExpectedAtAdmission { get; set; }
        public bool? Screen_IsDeathExpectedAtTimeOfDeath { get; set; }
        public bool? Screen_IsSepsis { get; set; }
        public bool? Screen_IsReadmittedWithin30Days { get; set; }
        [Unicode(false)]
        public string Screen_SummaryOfDeath { get; set; }
        public bool? Pr_IsNeeded { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Pr_DtInitiated { get; set; }
        public int? Pr_ProviderId1 { get; set; }
        public int? Pr_ProviderId2 { get; set; }
        public int? Pr_ProviderId3 { get; set; }
        public bool? PrSource_IsRl6 { get; set; }
        public bool? Pr_Source_IsMM { get; set; }
        public int? Pr_Source_MM_DeptId { get; set; }
        public bool? Pr_Source_IsScreening { get; set; }
        public bool? Pr_Source_IsOther { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string Pr_Source_Other_Text { get; set; }
        public bool? Pr_Refer_IsToDept { get; set; }
        public int? Pr_Refer_DeptId { get; set; }
        public bool? Pr_Refer_IsToMulti { get; set; }
        public bool? Pr_Refer_IsToSse { get; set; }
        public bool? Outcome_IsOpportunityForImprovement { get; set; }
        public bool? Outcome_IsProviderConcern { get; set; }
        public int? Outcome_ProviderConcern_ProviderId1 { get; set; }
        public int? Outcome_ProviderConcern_ProviderId2 { get; set; }
        public bool? Outcome_IsSystemConcern { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string Outcome_SystemOfConcernNote { get; set; }
        public bool? Outcome_IsNursingConcern { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string Outcome_NursingConcernNote { get; set; }
        public bool? Outcome_IsLeadershipCouncilReview { get; set; }
        [Unicode(false)]
        public string Outcome_Note { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTs { get; set; }
    }
}