// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class SafetyEvent
    {
        [Key]
        public int safetyEventId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? eventDt { get; set; }
        public int? facilityId { get; set; }
        [StringLength(300)]
        [Unicode(false)]
        public string typeGeneral { get; set; }
        [StringLength(300)]
        [Unicode(false)]
        public string typeSpecific { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string personAffectedType { get; set; }
        [StringLength(1200)]
        [Unicode(false)]
        public string briefDescription { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string dept { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string classification { get; set; }
        [Unicode(false)]
        public string comment { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string inlineNote { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string status { get; set; }
        public int? memberIdAssigned { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string assetURL { get; set; }
        public int? mrn { get; set; }
        public int? fin { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string personAffected { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string rl6CaseIdDelim { get; set; }
        [StringLength(1000)]
        [Unicode(false)]
        public string qrtCaseIdDelim { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime createTs { get; set; }
        public int? memberIdCreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? deleteTs { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? memberIdDeletedBy { get; set; }
        [StringLength(10)]
        [Unicode(false)]
        public string grouping { get; set; }


        public string npiProviderAttending { get; set; }


        public string npiProviderAssoc { get; set; }
        



    }
}