// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class SmileFeedback
    {
        [Key]
        public int SmileFeedbackId { get; set; }
        public int SourceAssetId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string FeedbackValue { get; set; }
        [StringLength(2000)]
        [Unicode(false)]
        public string FeedbackOneWord { get; set; }
        [StringLength(4000)]
        [Unicode(false)]
        public string FeedbackComment { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string ReviewerEmail { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string ReviewerPhone { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTs { get; set; }
    }
}