// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace UsaWeb.Service.Models
{
    public partial class sp_GetWordsByFilterResult
    {
        public string word { get; set; }
        public int? tCount { get; set; }
    }
}
