// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace UsaWeb.Service.Models
{
    public partial class sp_GetWordsPieByFilterResult
    {
        public string reaction { get; set; }
        public int? tcount { get; set; }
    }
}
