// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace UsaWeb.Service.Models
{
    public partial class sp_GetSS_RawResultResult
    {
        public string surg_case_nbr { get; set; }
        public int? BatchId { get; set; }
        public int? MRN { get; set; }
        public int? FIN { get; set; }
        public string patient_first_name { get; set; }
        public string patient_last_name { get; set; }
        public string location { get; set; }
        public string home_phone { get; set; }
        public string cell_phone { get; set; }
        public string pat_addr1 { get; set; }
        public string pat_addr2 { get; set; }
        public string pat_addr_city { get; set; }
        public string pat_addr_st { get; set; }
        public int? pat_addr_zip { get; set; }
        public string patient_email { get; set; }
        public string surgeon { get; set; }
        public string surg_case_spec { get; set; }
        public string call1_complete { get; set; }
        public string call1_complete_user { get; set; }
        public string call2_complete { get; set; }
        public string call2_complete_user { get; set; }
        public DateTime? callpo_complete { get; set; }
        public string callpo_complete_user { get; set; }
        public DateTime? call1_attempt { get; set; }
        public string call1_attempt_user { get; set; }
        public string call2_attempt { get; set; }
        public string call2_attempt_user { get; set; }
        public string call3_attempt { get; set; }
        public string call3_attempt_user { get; set; }
        public string callpo_attempt { get; set; }
        public string callpo_attempt_user { get; set; }
        public string call_pat_left_mes { get; set; }
        public string call_pat_left_mes_user { get; set; }
        public string call_pat_req_callback { get; set; }
        public string call_pat_req_callback_user { get; set; }
        public string covid_outside_test_dt_tm { get; set; }
        public string covid_outside_test_user { get; set; }
        public DateTime? PCR { get; set; }
        public string pcr_user { get; set; }
        public string pcr_notes { get; set; }
        public string days_until_surg { get; set; }
        public string days_between { get; set; }
        public DateTime? surg_create_dt_tm { get; set; }
        public DateTime? date_of_service { get; set; }
        public DateTime? apt_dt_tm { get; set; }
        public string appointment_rescheduled { get; set; }
        public string cancel_dt_tm { get; set; }
        public string anticoagplat { get; set; }
        public string surg_risk_score { get; set; }
        public string case_proc_name { get; set; }
        public string ASA_class { get; set; }
        public string dept { get; set; }
        public int? encounter_id { get; set; }
        public string surgical_note { get; set; }
        public string covid_vacc_type { get; set; }
        public DateTime? _1st_covid_vacc_dt_tm { get; set; }
        public DateTime? _2nd_covid_vacc_dt_tm { get; set; }
        public string patient_language { get; set; }
        public DateTime? dob { get; set; }
        public string NoteLatestText { get; set; }
        public string Status { get; set; }
        public DateTime? Call1CompletedTs { get; set; }
        public DateTime? Call2CompletedTs { get; set; }
        public DateTime? ArrivalTs { get; set; }
        public int? MemberIdAssigned { get; set; }
        public string Call1Name { get; set; }
        public string Call2Name { get; set; }
        public DateTime? ClearanceNeededPulmonaryTs { get; set; }
        public DateTime? ClearanceNeededPulmonaryCompleteTs { get; set; }
        public DateTime? ClearanceNeededCardioTs { get; set; }
        public DateTime? ClearanceNeededCardioCompleteTs { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string TagColor { get; set; }
        public int? arrivalDiff { get; set; }
    }
}
