// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace UsaWeb.Service.Models
{
    public partial class sp_GetSS_CallsByMrnResult
    {
        public int SurgicalScheduleCallId { get; set; }
        public string sug_case_nbr { get; set; }
        public DateTime CreateTs { get; set; }
        public int MemberId { get; set; }
        public string CallResult { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public string FullName { get; set; }
    }
}
