// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    [Keyless]
    [Index("surgeon", Name = "_dta_index_SurgicalScheduleRaw_7_565577053__K16")]
    [Index("surg_case_spec", Name = "_dta_index_SurgicalScheduleRaw_7_565577053__K17")]
    [Index("MRN", "surg_create_dt_tm", Name = "_dta_index_SurgicalScheduleRaw_7_565577053__K3_K43D_1_2_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_")]
    public partial class SurgicalScheduleRaw
    {
        [StringLength(50)]
        public string surg_case_nbr { get; set; }
        public int? BatchId { get; set; }
        public int? MRN { get; set; }
        public int? FIN { get; set; }
        [StringLength(50)]
        public string patient_first_name { get; set; }
        [StringLength(50)]
        public string patient_last_name { get; set; }
        [StringLength(50)]
        public string location { get; set; }
        [StringLength(50)]
        public string home_phone { get; set; }
        [StringLength(50)]
        public string cell_phone { get; set; }
        [StringLength(50)]
        public string pat_addr1 { get; set; }
        [StringLength(50)]
        public string pat_addr2 { get; set; }
        [StringLength(50)]
        public string pat_addr_city { get; set; }
        [StringLength(50)]
        public string pat_addr_st { get; set; }
        public int? pat_addr_zip { get; set; }
        [StringLength(50)]
        public string patient_email { get; set; }
        [StringLength(50)]
        public string surgeon { get; set; }
        [StringLength(50)]
        public string surg_case_spec { get; set; }
        [StringLength(50)]
        public string call1_complete { get; set; }
        [StringLength(50)]
        public string call1_complete_user { get; set; }
        [StringLength(50)]
        public string call2_complete { get; set; }
        [StringLength(50)]
        public string call2_complete_user { get; set; }
        public DateTime? callpo_complete { get; set; }
        [StringLength(50)]
        public string callpo_complete_user { get; set; }
        public DateTime? call1_attempt { get; set; }
        [StringLength(50)]
        public string call1_attempt_user { get; set; }
        [StringLength(50)]
        public string call2_attempt { get; set; }
        [StringLength(50)]
        public string call2_attempt_user { get; set; }
        [StringLength(50)]
        public string call3_attempt { get; set; }
        [StringLength(50)]
        public string call3_attempt_user { get; set; }
        [StringLength(50)]
        public string callpo_attempt { get; set; }
        [StringLength(50)]
        public string callpo_attempt_user { get; set; }
        [StringLength(50)]
        public string call_pat_left_mes { get; set; }
        [StringLength(50)]
        public string call_pat_left_mes_user { get; set; }
        [StringLength(50)]
        public string call_pat_req_callback { get; set; }
        [StringLength(50)]
        public string call_pat_req_callback_user { get; set; }
        [StringLength(50)]
        public string covid_outside_test_dt_tm { get; set; }
        [StringLength(50)]
        public string covid_outside_test_user { get; set; }
        public DateTime? PCR { get; set; }
        [StringLength(50)]
        public string pcr_user { get; set; }
        [StringLength(50)]
        public string pcr_notes { get; set; }
        [StringLength(50)]
        public string days_until_surg { get; set; }
        [StringLength(50)]
        public string days_between { get; set; }
        public DateTime? surg_create_dt_tm { get; set; }
        public DateTime? date_of_service { get; set; }
        public DateTime? apt_dt_tm { get; set; }
        [StringLength(50)]
        public string appointment_rescheduled { get; set; }
        [StringLength(50)]
        public string cancel_dt_tm { get; set; }
        [StringLength(50)]
        public string anticoagplat { get; set; }
        [StringLength(1)]
        public string surg_risk_score { get; set; }
        [StringLength(50)]
        public string case_proc_name { get; set; }
        [StringLength(50)]
        public string ASA_class { get; set; }
        [StringLength(50)]
        public string dept { get; set; }
        public int? encounter_id { get; set; }
        [StringLength(4000)]
        public string surgical_note { get; set; }
        [StringLength(50)]
        public string covid_vacc_type { get; set; }
        public DateTime? _1st_covid_vacc_dt_tm { get; set; }
        public DateTime? _2nd_covid_vacc_dt_tm { get; set; }
        [StringLength(500)]
        [Unicode(false)]
        public string patient_language { get; set; }
        [Column(TypeName = "date")]
        public DateTime? dob { get; set; }
    }
}