// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class SurgicalScheduleExtended
    {
        [Key]
        public int SurgicalScheduleExtendedId { get; set; }
        [Required]
        [StringLength(50)]
        public string surg_case_nbr { get; set; }
        public int? MemberIdAssigned { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CompletedTs { get; set; }
        [Unicode(false)]
        public string PaperText { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ComeAliveDate { get; set; }
        [Unicode(false)]
        public string ComeAliveNote { get; set; }
        [Unicode(false)]
        public string NoteLatestText { get; set; }
        public int? NoteCreatedByMemberId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? NoteCreatedByTs { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdatedTs { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreateTs { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Call1CompletedTs { get; set; }
        public int? Call1CompletedMemberId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Call2CompletedTs { get; set; }
        public int? Call2CompletedMemberId { get; set; }
        public int? CallNoAnswerCount { get; set; }
        public int? CallVoicemailCount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ArrivalTs { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ClearanceNeededPulmonaryTs { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ClearanceNeededPulmonaryCompleteTs { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ClearanceNeededCardioTs { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ClearanceNeededCardioCompleteTs { get; set; }
    }
}