// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class SurgicalScheduleCall
    {
        [Key]
        public int SurgicalScheduleCallId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string sug_case_nbr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateTs { get; set; }
        public int MemberId { get; set; }
        /// <summary>
        /// COMPLETE, LEFT_VMAIL, NO_ANSWER, CALLBACK_REQ, 
        /// </summary>
        [Required]
        [StringLength(30)]
        [Unicode(false)]
        public string CallResult { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Value1 { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Value2 { get; set; }
    }
}