// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    [Keyless]
    public partial class WordResponseRaw
    {
        [StringLength(50)]
        [Unicode(false)]
        public string Service { get; set; }
        [Column("Client ID")]
        [StringLength(50)]
        [Unicode(false)]
        public string Client_ID { get; set; }
        [Column("Site Name")]
        [StringLength(50)]
        [Unicode(false)]
        public string Site_Name { get; set; }
        [Column("Was this your first visit here")]
        [StringLength(50)]
        [Unicode(false)]
        public string Was_this_your_first_visit_here { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Comment { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Reaction { get; set; }
        [Column("Provider ID")]
        [StringLength(50)]
        [Unicode(false)]
        public string Provider_ID { get; set; }
        [Column("IT MD_NAME")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_MD_NAME { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Specialty { get; set; }
        [Column("Clean Comment")]
        [StringLength(50)]
        [Unicode(false)]
        public string Clean_Comment { get; set; }
        [Column("Word Count")]
        [StringLength(50)]
        [Unicode(false)]
        public string Word_Count { get; set; }
        [Column("One Word?")]
        [StringLength(50)]
        [Unicode(false)]
        public string One_Word_ { get; set; }
        [Column("Contains Exclamation?")]
        [StringLength(50)]
        [Unicode(false)]
        public string Contains_Exclamation_ { get; set; }
        [Column("Patient Name")]
        [StringLength(50)]
        [Unicode(false)]
        public string Patient_Name { get; set; }
        [Column("Patient Phone")]
        [StringLength(50)]
        [Unicode(false)]
        public string Patient_Phone { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Section { get; set; }
        [Column("Comment Question")]
        [StringLength(50)]
        [Unicode(false)]
        public string Comment_Question { get; set; }
        [Column("Survey Barcode")]
        [StringLength(50)]
        [Unicode(false)]
        public string Survey_Barcode { get; set; }
        [Column("Received Date")]
        [StringLength(50)]
        [Unicode(false)]
        public string Received_Date { get; set; }
        [Column("Service Date")]
        [StringLength(50)]
        [Unicode(false)]
        public string Service_Date { get; set; }
        [Column("Recorded Date")]
        [StringLength(50)]
        [Unicode(false)]
        public string Recorded_Date { get; set; }
        [Column("Adjusted Sample")]
        [StringLength(50)]
        [Unicode(false)]
        public string Adjusted_Sample { get; set; }
        [Column("IT ADDR2")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_ADDR2 { get; set; }
        [Column("IT ADM_DATE")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_ADM_DATE { get; set; }
        [Column("IT ADM_LOC")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_ADM_LOC { get; set; }
        [Column("IT ADM_TIME")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_ADM_TIME { get; set; }
        [Column("IT AGE")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_AGE { get; set; }
        [Column("IT CITY")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_CITY { get; set; }
        [Column("IT CLINIC")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_CLINIC { get; set; }
        [Column("IT clinic Cd")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_clinic_Cd { get; set; }
        [Column("IT DCG_CD")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_DCG_CD { get; set; }
        [Column("IT DCG_DATE")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_DCG_DATE { get; set; }
        [Column("IT DCG_TIME")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_DCG_TIME { get; set; }
        [Column("IT DISDATE")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_DISDATE { get; set; }
        [Column("IT EMAILFLG")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_EMAILFLG { get; set; }
        [Column("IT ENC_TYPE")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_ENC_TYPE { get; set; }
        [Column("IT E_FLAG")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_E_FLAG { get; set; }
        [Column("IT FN_CLASS")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_FN_CLASS { get; set; }
        [Column("IT LANGUAGE")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_LANGUAGE { get; set; }
        [Column("IT MD_SPEC")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_MD_SPEC { get; set; }
        [Column("IT MD_TYPE")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_MD_TYPE { get; set; }
        [Column("IT NPI")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_NPI { get; set; }
        [Column("IT PAYOR")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_PAYOR { get; set; }
        [Column("IT RACE")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_RACE { get; set; }
        [Column("IT ROOM")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_ROOM { get; set; }
        [Column("IT SERVICE")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_SERVICE { get; set; }
        [Column("IT SERV_TYP")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_SERV_TYP { get; set; }
        [Column("IT SEX")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_SEX { get; set; }
        [Column("IT SITE")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_SITE { get; set; }
        [Column("IT SITE_CD")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_SITE_CD { get; set; }
        [Column("IT SITE_ID")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_SITE_ID { get; set; }
        [Column("IT SPECIAL")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_SPECIAL { get; set; }
        [Column("IT STATE")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_STATE { get; set; }
        [Column("IT SVC_DATE")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_SVC_DATE { get; set; }
        [Column("IT TELE_MED")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_TELE_MED { get; set; }
        [Column("IT UNIT")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_UNIT { get; set; }
        [Column("IT ZIP")]
        [StringLength(50)]
        [Unicode(false)]
        public string IT_ZIP { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Language { get; set; }
        [Column("Minutes wait for exam room")]
        [StringLength(50)]
        [Unicode(false)]
        public string Minutes_wait_for_exam_room { get; set; }
        [Column("Minutes wait for exam room^")]
        [StringLength(50)]
        [Unicode(false)]
        public string Minutes_wait_for_exam_room_ { get; set; }
        [Column("Minutes wait in exam room to see CP")]
        [StringLength(50)]
        [Unicode(false)]
        public string Minutes_wait_in_exam_room_to_see_CP { get; set; }
        [Column("Minutes wait in exam room to see C^")]
        [StringLength(50)]
        [Unicode(false)]
        public string Minutes_wait_in_exam_room_to_see_C_ { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Mode { get; set; }
        [Column("Patient's age")]
        [StringLength(50)]
        [Unicode(false)]
        public string Patient_s_age { get; set; }
        [Column("Patient's age^")]
        [StringLength(50)]
        [Unicode(false)]
        public string Patient_s_age_ { get; set; }
        [Column("Patient's sex gender")]
        [StringLength(50)]
        [Unicode(false)]
        public string Patient_s_sex_gender { get; set; }
        [Column("Pediatric versioning")]
        [StringLength(50)]
        [Unicode(false)]
        public string Pediatric_versioning { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string REVISION { get; set; }
        [Column("Site id")]
        [StringLength(50)]
        [Unicode(false)]
        public string Site_id { get; set; }
        [Column("Time call completed")]
        [StringLength(50)]
        [Unicode(false)]
        public string Time_call_completed { get; set; }
    }
}