// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class Word
    {
        [Key]
        [Column("Word")]
        [StringLength(500)]
        [Unicode(false)]
        public string Word1 { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Reaction { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string Subject { get; set; }
    }
}