// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UsaWeb.Service.Models
{
    public partial class WordResponse
    {
        [Key]
        public int WordResponseId { get; set; }
        [Required]
        [StringLength(5000)]
        [Unicode(false)]
        public string Word { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string Reaction { get; set; }
        [StringLength(400)]
        [Unicode(false)]
        public string Provider { get; set; }
        [StringLength(400)]
        [Unicode(false)]
        public string Specialty { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ServiceDt { get; set; }
        [Column(TypeName = "date")]
        public DateTime? ReceivedDt { get; set; }
        [StringLength(200)]
        [Unicode(false)]
        public string SiteName { get; set; }
        public int? MinuteWaitExamRoom { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string MinuteWaitExamRoomRange { get; set; }
        public int? MinuteWaitToSeeCp { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string MinuteWaitToSeeCpRange { get; set; }
        [StringLength(400)]
        [Unicode(false)]
        public string PatientName { get; set; }
        [StringLength(400)]
        [Unicode(false)]
        public string PatientPhone { get; set; }
        public int? PatientAge { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string PatientAgeRange { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string PatientSex { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Fin { get; set; }
    }
}