name: .NET Core Deploy to IIS

on:
  workflow_dispatch:

jobs:
  build-test-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      
      - name: List Solution Contents
        shell: cmd
        run: |
          dir /s /b *.sln
          dir /s /b *.csproj
      
      # Build UsaWeb.Service
      - name: Build UsaWeb.Service
        shell: cmd
        run: |
          dotnet build Vez/UsaWeb.Service/UsaWeb.Service.csproj --configuration Release
      
      # Build and Test UsaWeb.Service.UnitTests
      - name: Build and Test UsaWeb.Service.UnitTests
        shell: cmd
        run: |
          dotnet build Vez/UsaWeb.Service.UnitTests/UsaWeb.Service.UnitTests.csproj --configuration Release
          dotnet test Vez/UsaWeb.Service.UnitTests/UsaWeb.Service.UnitTests.csproj --configuration Release --no-build --verbosity normal
      
      # Publish projects if tests pass
      - name: Publish UsaWeb.Service
        shell: cmd
        run: dotnet publish Vez/UsaWeb.Service/UsaWeb.Service.csproj -c Release -o .\publish\UsaWebService
        
      # Deploy if all previous steps succeed
      - name: Deploy UsaWeb.Service to IIS
        shell: cmd
        run: |
          iisreset /stop
          xcopy /S /Y .\publish\UsaWebService C:\web\vez.service
          iisreset /start
